version: "3"

services:
  db:
    image: "postgres:alpine"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dummypassword
      - POSTGRES_DB=tax_calculator
    networks:
      - backend
  app:
    build: "."
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    command: >
      bash -c "./build/tax-calculator migrate &&
              ./build/tax-calculator start"
    networks:
      - backend

networks:
  backend:
    driver: bridge