// Code generated by mockery v1.0.0
package mocks

import controller "github.com/kemalelmizan/tax-calculator/src/controller"
import mock "github.com/stretchr/testify/mock"

// ProductController is an autogenerated mock type for the ProductController type
type ProductController struct {
	mock.Mock
}

// PostProduct provides a mock function with given fields: _a0
func (_m *ProductController) PostProduct(_a0 []controller.ProductInput) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]controller.ProductInput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
