// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/kemalelmizan/tax-calculator/src/model"

// ProductModel is an autogenerated mock type for the ProductModel type
type ProductModel struct {
	mock.Mock
}

// InsertProducts provides a mock function with given fields: _a0
func (_m *ProductModel) InsertProducts(_a0 []model.Product) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Product) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectProductsFromNames provides a mock function with given fields: _a0
func (_m *ProductModel) SelectProductsFromNames(_a0 []string) ([]model.Product, error) {
	ret := _m.Called(_a0)

	var r0 []model.Product
	if rf, ok := ret.Get(0).(func([]string) []model.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
